AWen/AWen.TaskManager.Web/Controllers/BaseController.cs
/********************************************************************
 * 命名空间: AWen.TaskManager.Web.Controllers

 * 文件名称: BaseController

 * 文件作者: AWen

 * 创建时间: 2018/4/18 10:45:21
=====================================================================
 * 功能说明:
---------------------------------------------------------------------
 * 其他说明:
*********************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using AWen.TaskManager.Web;

namespace AWen.TaskManager.Web.Controllers
{
    public class BaseController : Controller
    {
        #region JsonResult

        public new JsonResult Json(object data)
        {
            return new NewtonJsonResult(data, new JsonSerializerSettings() { DateFormatString = "yyyy-MM-dd HH:mm:ss" });
        }

        public new JsonResult Json(object data, JsonRequestBehavior behavior)
        {
            return new NewtonJsonResult(data, behavior, new JsonSerializerSettings() { DateFormatString = "yyyy-MM-dd HH:mm:ss" });
        }

        public JsonResult Json(object data, JsonRequestBehavior behavior, string DateFormatString)
        {
            return new NewtonJsonResult(data, behavior, new JsonSerializerSettings() { DateFormatString = DateFormatString });
        }

        public new JsonResult Json(object data, string DateFormatString)
        {
            return new NewtonJsonResult(data, new JsonSerializerSettings() { DateFormatString = DateFormatString });
        }

        #endregion
	}
}

AWen/AWen.TaskManager.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AWen.TaskManager.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AWen/AWen.TaskManager.Web/Controllers/TaskInfoController.cs
using AWen.TaskManager.Core.BLL;
using AWen.TaskManager.Core.Model;
using System;
using System.Linq;
using System.Web.Mvc;

namespace AWen.TaskManager.Web.Controllers
{
    public class TaskInfoController : BaseController
    {
        private TaskInfoService _TaskInfoService;

        public TaskInfoController()
        {
            _TaskInfoService = new TaskInfoService();
        }

        [HttpGet]
        public ActionResult List(int page, int limit, string search)
        {
            var totaldata = _TaskInfoService.GetModelList("  where IsDelete=0 and TaskName Like N'%" + search + "%'  ", null);
            var data = _TaskInfoService.GetListPage(page, limit, "  where IsDelete=0 and TaskName Like N'%" + search + "%'  ", "TaskId desc", null);
            var result = new ResponseResult() { success = true, count = totaldata.Count(), message = "数据获取成功", data = data };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /TaskInfo/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Info(int id)
        {
            var model = _TaskInfoService.GetModel(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult AddPost(TB_TM_TaskInfo Info)
        {
            var result = new ResponseResult();
            //Info.BackgroundJobId = System.Guid.NewGuid();
            result.success = _TaskInfoService.Add(Info);
            return Json(result);
        }

        [HttpPost]
        public ActionResult UpateState(int id, int state)
        {
            var result = new ResponseResult();
            var model = _TaskInfoService.GetModel(id);
            model.State = state;
            result.success = _TaskInfoService.Update(model);
            result.message = result.success == true ? "操作成功" : "操作失败";
            return Json(result);
        }

        [HttpPost]
        public ActionResult UpateImmedRun(int id, int immedRun)
        {
            var result = new ResponseResult();
            var model = _TaskInfoService.GetModel(id);
            model.ImmedRun = immedRun;
            result.success = _TaskInfoService.Update(model);
            result.message = result.success == true ? "操作成功" : "操作失败";
            return Json(result);
        }

        [HttpPost]
        public ActionResult UpatePost(TB_TM_TaskInfo Info)
        {
            var result = new ResponseResult();
            result.success = _TaskInfoService.Update(Info);
            result.message = result.success == true ? "操作成功" : "操作失败";

            return Json(result);
        }

        [HttpPost]
        public ActionResult Delete(string idList)
        {
            var result = new ResponseResult();
            try
            {
                var idArray = idList.Split(',');
                foreach (var id in idArray)
                {
                    var model = _TaskInfoService.GetModel(int.Parse(id));
                    model.IsDelete = 1;
                    _TaskInfoService.Update(model);
                }
                result.success = true;
                result.message = "操作成功";
            }
            catch (Exception ex)
            {
                result.message = ex.Message;
            }
            return Json(result);
        }

        [HttpGet]
        public ActionResult InfoData(int id)
        {
            var result = new ResponseResult();
            result.data = _TaskInfoService.GetModel(id);
            result.success = true;
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

AWen/AWen.TaskManager.Web/Controllers/TaskLogController.cs
using AWen.TaskManager.Core.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AWen.TaskManager.Web.Controllers
{
    public class TaskLogController : BaseController
    {
        private TaskLogService _TaskLogService;

        public TaskLogController()
        {
            _TaskLogService = new TaskLogService();
        }

        [HttpGet]
        public ActionResult List(int page, int limit, string search)
        {
            var totaldata = _TaskLogService.GetModelList(" where IsDelete=0 and TaskName Like N'%" + search + "%' ", null);
            var data = _TaskLogService.GetListPage(page, limit, " where IsDelete=0 and TaskName Like N'%" + search + "%' ", "TaskLogId desc", null);
            var result = new ResponseResult() { success = true,count=totaldata.Count(), message = "数据获取成功", data = data };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /TaskInfo/
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(string idList)
        {
            var result = new ResponseResult();
            try
            {
                var idArray = idList.Split(',');
                foreach (var id in idArray)
                {
                    var model = _TaskLogService.GetModel(int.Parse(id));
                    model.IsDelete = 1;
                    _TaskLogService.Update(model);
                }
                result.success = true;
                result.message = "操作成功";
            }
            catch (Exception ex)
            {
                result.message = ex.Message;
            }
            return Json(result);
        }
	}
}

AWen/AWen.TaskManager.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AWen/AWen.TaskManager.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AWen/AWen.TaskManager.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@*<h2>时间线</h2>*@
<ul class="layui-timeline">

    <li class="layui-timeline-item">
        <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
        <div class="layui-timeline-content layui-text">
            <h3 class="layui-timeline-title">未来</h3>
            <p>进一步完善很多功能：</p>
            <ul>
                <li>权限管理</li>
                <li>菜单管理</li>
                <li>任务管理</li>
            </ul>
        </div>
    </li>
    <li class="layui-timeline-item">
        <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
        <div class="layui-timeline-content layui-text">
            <h3 class="layui-timeline-title">现在</h3>
            <p>
                目前进行中的是任务管理,设计技术
            </p>
            <ul>
                <li>Quartz</li>
                <li>Topshelf</li>
                <li>Dapper</li>
            </ul>
        </div>
    </li>
    <li class="layui-timeline-item">
        <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
        <div class="layui-timeline-content layui-text">
            <div class="layui-timeline-title">过去</div>

            <p>
               什么都没有。。。。。
            </p>
        </div>
    </li>
</ul>

AWen/AWen.TaskManager.Web/Views/Shared/_Layout_Dialog.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 任务管理平台</title>
    <!--[if lt IE 8]>
    <script>
        alert('站点 不支持IE6-8，请使用谷歌、火狐等浏览器\n或360、QQ等国产浏览器的极速模式浏览本页面！');
    </script>
    <![endif]-->
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" />
    <script src="~/Content/jquery/jquery-2.1.1.min.js"></script>
    <script src="~/Content/layui/layui.js"></script>
    <script type="text/javascript">
        //由于模块都一次性加载，因此不用执行 layui.use() 来加载对应模块，直接使用即可：
        //; !function () {
        //    var layer = layui.layer
        //    , form = layui.form
        //    , element = layui.element;

        //    //layer.msg('Hello World');
        //}();

        //JavaScript代码区域
        layui.use('element', function () {
            var element = layui.element;
        });
        layui.use('form', function () {
            var form = layui.form;

          
        });
    </script>
    @RenderSection("CSS", false)
</head>
<body>
    <div class="layui-fluid" style="padding-top:10px">

        @RenderBody()
    </div>

    @RenderSection("JS", required: false)
</body>
</html>

AWen/AWen.TaskManager.Web/Views/Shared/_Layout_List.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 任务管理平台</title>
    <!--[if lt IE 8]>
    <script>
        alert('站点 不支持IE6-8，请使用谷歌、火狐等浏览器\n或360、QQ等国产浏览器的极速模式浏览本页面！');
    </script>
    <![endif]-->
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" />
    <script src="~/Content/jquery/jquery-2.1.1.min.js"></script>
    <script src="~/Content/layui/layui.js"></script>
    <script type="text/javascript">
        //由于模块都一次性加载，因此不用执行 layui.use() 来加载对应模块，直接使用即可：
        //; !function () {
        //    var layer = layui.layer
        //    , form = layui.form
        //    , element = layui.element;

        //    //layer.msg('Hello World');
        //}();

        //JavaScript代码区域
        layui.use('element', function () {
            var element = layui.element;
        });
        layui.use('form', function () {
            var form = layui.form;

           
        });
    </script>
    @RenderSection("CSS", false)
</head>
<body class="layui-layout-body">
    <div class="layui-layout layui-layout-admin">
        <div class="layui-header">
            <div class="layui-logo">AWen 任务管理平台</div>
            <!-- 头部区域（可配合layui已有的水平导航） -->
            <ul class="layui-nav layui-layout-left">
                <li class="layui-nav-item"><a href="@Url.Action("Index","Home")">首页</a></li>
                @*<li class="layui-nav-item"><a href="">任务控制台</a></li>
                <li class="layui-nav-item"><a href="">用户管理</a></li>
                <li class="layui-nav-item">
                    <a href="javascript:;">其它系统</a>
                    <dl class="layui-nav-child">
                        <dd><a href="">邮件管理</a></dd>
                        <dd><a href="">消息管理</a></dd>
                        <dd><a href="">授权管理</a></dd>
                    </dl>
                </li>*@
            </ul>
            <ul class="layui-nav layui-layout-right">
                <li class="layui-nav-item">
                    <a href="javascript:;">
                        @*<img src="http://t.cn/RCzsdCq" class="layui-nav-img">*@
                        <i class="layui-icon" style="font-size: 20px;">&#xe612;</i>
                        AWen
                    </a>
                    <dl class="layui-nav-child">
                        <dd><a href="">基本资料</a></dd>
                        <dd><a href="">安全设置</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item"><a href="">退出</a></li>
            </ul>
        </div>
        <div class="layui-side layui-bg-black">
            <div class="layui-side-scroll">
                <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
                <ul class="layui-nav layui-nav-tree" lay-filter="test">
                    <li class="layui-nav-item layui-nav-itemed">
                        <a class="" href="javascript:void(0);">后台任务</a>
                        <dl class="layui-nav-child">
                            <dd><a href="@Url.Action("Index","TaskInfo")">任务管理</a></dd>
                            <dd><a href="@Url.Action("Index","TaskLog")">运行日志</a></dd>
                            <dd><a href="http://cron.qqe2.com/">Cron生成器</a></dd>
                        </dl>
                    </li>
                    @*<li class="layui-nav-item">
                        <a href="javascript:;">解决方案</a>
                        <dl class="layui-nav-child">
                            <dd><a href="javascript:;">列表一</a></dd>
                            <dd><a href="javascript:;">列表二</a></dd>
                            <dd><a href="">超链接</a></dd>
                        </dl>
                    </li>
                    <li class="layui-nav-item"><a href="">云市场</a></li>
                    <li class="layui-nav-item"><a href="">发布商品</a></li>*@
                </ul>
            </div>
        </div>
        <div class="layui-body">
            <!-- 内容主体区域 -->
            <div class="layui-fluid" style="padding-top:10px">
                
                    @RenderBody()
             
            </div>
        </div>
        <div class="layui-footer">
            <!-- 底部固定区域 -->
            <div class="right">
                <p>&copy; @DateTime.Now.Year - 任务管理平台</p>
            </div>
        </div>
    </div>
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("JS", required: false)
</body>
</html>

AWen/AWen.TaskManager.Web/Views/TaskInfo/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout_Dialog.cshtml";
}
<div class="layui-row">
    <div class="layui-col-sm-12">
        <form class="layui-form" id="form" action="@Url.Action("AddPost", "TaskInfo")" method="post">

            <div class="layui-form-item">
                <label class="layui-form-label">名称：</label>
                <div class="layui-input-block">
                    <input id="TaskName" name="TaskName" class="layui-input" type="text" required lay-verify="required" placeholder="请输入名称" />
                </div>
            </div>
            <div class="layui-form-item ">
                <label class="layui-form-label">类型：</label>
                <div class="layui-input-block">
                    <select id="TaskType" name="TaskType" required lay-verify="required" placeholder="请输入类型">
                        <option value=""></option>
                        @{foreach (var item in Enum.GetNames(typeof(AWen.TaskManager.Core.Common.TaskType)))
                        {

                            <option value="@item.ToString()">@item.ToString()</option>

                        }
                        }
                    </select>
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">程序集：</label>
                <div class="layui-input-block">
                    <input id="AssemblyName" name="AssemblyName" class="layui-input" type="text" required lay-verify="required" placeholder="请输入程序集名称"/>
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">类名：</label>
                <div class="layui-input-block">
                    <input id="ClassName" name="ClassName" class="layui-input" type="text" required lay-verify="required" placeholder="请输入类名" />
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">描述：</label>
                <div class="layui-input-block">
                    <textarea id="Description" name="Description" class="layui-textarea" ></textarea>
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">首次运行时间：</label>
                <div class="layui-input-block">
                    <input id="FirstRunTime" name="FirstRunTime" class="layui-input" type="text"  />
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">参数：</label>
                <div class="layui-input-block">
                    <input id="TaskArgs" name="TaskArgs" class="layui-input" type="text" />
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">Cron表达式：</label>
                <div class="layui-input-block">
                    <input id="CronExpression" name="CronExpression" class="layui-input" type="text" required lay-verify="required" placeholder="请输入Cron表达式" /> 
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">Cron表达式描述：</label>
                <div class="layui-input-block">
                    <textarea id="CronExpressionDescription" name="CronExpressionDescription" class="layui-textarea" placeholder="请输入内容" ></textarea>
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" lay-submit lay-filter="formDemo">立即提交</button>
                    <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section JS{
    <script>
        layui.use('laydate', function () {
            var laydate = layui.laydate;

            //执行一个laydate实例
            laydate.render({
                elem: '#FirstRunTime' //指定元素
                 , type: 'datetime'
                , format: "yyyy-MM-dd HH:mm:ss"
            });
        });
    </script>
}


AWen/AWen.TaskManager.Web/Views/TaskInfo/Index.cshtml
@{
    ViewBag.Title = "任务管理";
}

<div class="layui-row">
    <div class="layui-col-md12">
        <fieldset class="layui-elem-field layui-field-title">
            <legend>任务列表</legend>
        </fieldset>
    </div>
</div>
<div class="layui-row">
    <div class="layui-col-md8">
        <div class="layui-inline">
            <label class="layui-form-label">任务名称:</label>
            <div class="layui-input-inline">
                <input type="text" name="search" id="search" placeholder="请输入任务名称" class="layui-input">
            </div>
            <button class="layui-btn layui-btn-normal" id="btnSearch">查询</button>
        </div>
    </div>
    <div class="layui-col-md4">
        <button class="layui-btn layui-btn-sm" id="add">任务创建</button>
        <button class="layui-btn layui-btn-sm layui-btn-danger" id="deletemore">删除</button>
    </div>
</div>
<div class="layui-row">
    <div class="layui-col-md12">
        <table id="demo" lay-filter="test"></table>
    </div>
</div>
@section JS{
    <script>
        layui.use('table', function () {
            var table = layui.table;

            //第一个实例
            table.render({
                id: 'demoTable'
                , elem: '#demo'
                , skin: 'row' //行边框风格
                , even: true //开启隔行背景
                //, size: 'sm' //小尺寸的表格
               , height: 650
               , limit: 15
               , limits: [10, 15, 20, 30, 50, 100]
               , url: '/TaskInfo/List/' //数据接口
               , where: { search: $("#search").val() } //{ search: $("#search").val() } //如果无需传递额外参数，可不加该参数
               , page: true //开启分页
               , cols: [[ //表头
                        { field: 'TaskId', title: 'ID', type: "checkbox", width: 50, fixed: 'left' }
                        , { fixed: 'left', width: 150, align: "center", title: '操作', toolbar: '#barDemo' }
                        , { field: 'TaskName', title: '名称', width: 120, sort: true, fixed: 'left' }
                        , { field: 'TaskType', title: '类型', width: 80, fixed: 'left' }
                        , { field: 'State', title: '状态', width: 80, templet: '#stateTpl', fixed: 'left' }
                        , { field: 'AssemblyName', title: '程序集/路径', width: 120 }
                        , { field: 'ClassName', title: '类名/方法', width: 120 }
                        , { field: 'Description', title: '描述', width: 200 }
                        , { field: 'TaskArgs', title: '参数', width: 80 }
                        , { field: 'CronExpression', title: 'Cron表达式', width: 120 }
                        , { field: 'FirstRunTime', title: '首次运行时间', width: 120 }
                        , { field: 'NextRunTime', title: '下次运行时间', width: 120 }
                        , { field: 'LastRunTime', title: '最后运行时间', width: 120 }
                        , { field: 'RunCount', title: '总运行次数', width: 80 }
                        , { field: 'Priority', title: '权重', width: 80 }
                        , { field: 'DisplayOrder', title: '排序码', width: 80 }
               ]]
            });

            table.on('tool(test)', function (obj) { //注：tool是工具条事件名，test是table原始容器的属性 lay-filter="对应的值"
                var data = obj.data; //获得当前行数据
                var layEvent = obj.event; //获得 lay-event 对应的值（也可以是表头的 event 参数对应的值）
                var tr = obj.tr; //获得当前行 tr 的DOM对象

                if (layEvent === 'setState') { //操作状态
                    $.ajax({
                        url: "@Url.Action("UpateState", "TaskInfo")",
                        data: { 'id': data.TaskId, 'state': data.State > 0 ? -10 : 10 },
                        type: "Post",
                        dataType: "json",
                        success: function (data) {
                            layer.msg(data.message);
                            if (data.success) {
                                table.reload("demoTable");
                            }

                        },
                        error: function (data) {
                            layer.msg('错误:' + data.message);
                        }
                    });

                    //do somehing
                } else if (layEvent === 'del') { //删除
                    layer.confirm('真的删除行吗?', function (index) {
                        obj.del(); //删除对应行（tr）的DOM结构，并更新缓存
                        layer.close(index);
                        //向服务端发送删除指令
                    });
                } else if (layEvent === 'edit') { //编辑
                    //do something

                    layer.open({
                        type: 2,
                        area: ['800px', '600px'],
                        content: "@Url.Action("Info", "TaskInfo")/" + data.TaskId //这里content是一个普通的String
                    });

                }
                else if (layEvent === 'setImmedRun') {
                    layer.confirm('真的要立刻运行该程序吗?', function (index) {
                        //向服务端发送删除指令
                        $.ajax({
                            url: "@Url.Action("UpateImmedRun", "TaskInfo")",
                            data: { 'id': data.TaskId, 'immedRun': 1 },
                            type: "Post",
                            dataType: "json",
                            success: function (data) {
                                layer.msg(data.message);
                                if (data.success) {
                                    table.reload("demoTable");
                                }

                            },
                            error: function (data) {
                                layer.msg('错误:' + data.message);
                            }
                        });
                        layer.close(index);
                       
                    });
                }
            });
            //table.on('checkbox(test)', function (obj) {
            //    console.log(obj.checked); //当前是否选中状态
            //    console.log(obj.data); //选中行的相关数据
            //    console.log(obj.type); //如果触发的是全选，则为：all，如果触发的是单选，则为：one
            //});
            $("#add").bind("click", function () {
                layer.open({
                    type: 2,
                    area: ['700px', '600px'],
                    content: "@Url.Action("Add", "TaskInfo")"  //这里content是一个普通的String
                });
            });
            $("#deletemore").bind("click", function () {
                var checkStatus = table.checkStatus('demoTable'); //test即为基础参数id对应的值

                if (checkStatus.data.length > 0) {
                    layer.confirm('真的删除行吗?', function (index) {
                        var idArray = new Array();
                        for (var i = 0; i < checkStatus.data.length; i++) {
                            idArray.push(checkStatus.data[i].TaskId)
                            if (checkStatus.data[i].State > 0) {
                                layer.msg(checkStatus.data[i].TaskName + "是启动中的任务不能删除");
                                return;
                            }
                        }
                        $.ajax({
                            url: "@Url.Action("Delete", "TaskInfo")",
                            data: { 'idList': idArray.join() },
                            type: "Post",
                            dataType: "json",
                            success: function (data) {
                                layer.msg(data.message);
                                if (data.success) {
                                    table.reload("demoTable");
                                }

                            },
                            error: function (data) {
                                layer.msg('错误:' + data.message);
                            }
                        });
                        layer.close(index);
                        //向服务端发送删除指令
                    });

                }
                else {
                    layer.msg("请选择行");
                }

            });
            $("#btnSearch").bind("click", function () {
                table.reload("demoTable", {
                    where: { search: $("#search").val() }//设定异步数据接口的额外参数
                });
            });
        });
    </script>
    <script type="text/html" id="barDemo">

        {{# if(d.State =="@((int)AWen.TaskManager.Core.Common.TaskState.Stopping)"
        || d.State == "@((int)AWen.TaskManager.Core.Common.TaskState.Stopped)"
        || d.State == "@((int)AWen.TaskManager.Core.Common.TaskState.Error)"
        || d.State == "@((int)AWen.TaskManager.Core.Common.TaskState.Initial)"
        ){ }}
        <a class="layui-btn layui-btn-xs    layui-btn-normal" lay-event="edit">编辑</a>
        <a class="layui-btn layui-btn-xs  layui-btn-normal" lay-event="setState">启用</a>
        {{#  } else {}}
        <a class="layui-btn layui-btn-xs layui-btn-warm" lay-event="setState">停用</a>
        <a class="layui-btn layui-btn-xs layui-btn-normal" lay-event="setImmedRun">立刻运行</a>
        {{#  } }}
    </script>
    <script type="text/html" id="stateTpl">
        {{#  if(d.State == "@((int)AWen.TaskManager.Core.Common.TaskState.Error)"){ }}
        <a class="layui-btn layui-btn-xs   layui-btn-danger">
            错误
        </a>
        {{#  } else  if(d.State == "@((int)AWen.TaskManager.Core.Common.TaskState.Stopped)") { }}
        <a class="layui-btn layui-btn-xs  layui-btn-warm">停止</a>
        {{#  } else  if(d.State == "@((int)AWen.TaskManager.Core.Common.TaskState.Stopping)") { }}
        <a class="layui-btn layui-btn-xs   layui-btn-warm">
            停止中...
        </a>
        {{#  } else  if(d.State == "@((int)AWen.TaskManager.Core.Common.TaskState.Starting)") { }}
        <a class="layui-btn layui-btn-xs  ">启动中...</a>
        {{#  } else  if(d.State ==  "@((int)AWen.TaskManager.Core.Common.TaskState.Running)") { }}
        <a class="layui-btn layui-btn-xs layui-btn-normal ">
            启动
        </a>
        {{#  } else  if(d.State ==  "@((int)AWen.TaskManager.Core.Common.TaskState.Initial)") { }}
        <a class="layui-btn layui-btn-xs layui-btn-normal ">
            初始化...
        </a>
        {{#  } else {}}
        <a class="layui-btn layui-btn-xs   layui-btn-primary">
            无效状态
        </a>
        {{#  } }}
    </script>

}